name: Docker Image CI

on:
  push:
    tags: 
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up variables
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
            
      - name: Build the Docker image
        run: | 
          echo ${{secrets.PAT}} | sudo docker login -u koteman123 --password-stdin
          sudo docker buildx create --use
          sudo docker buildx build --push -t koteman123/dj_sanya_go:${{ steps.vars.outputs.tag }} .
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          VERSION: ${{ steps.vars.outputs.tag }}
        with: 
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: VERSION
          script_stop: true
          script: CD dj_sanya_go && VERSION=${VERSION} ./start_sanya.sh 
