name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up variables
        id: vars
        run: echo ::set-output name=img::koteman123/dj_sanya_go:$(date +%s)
            
      - name: Build the Docker image
        run: | 
          echo ${{secrets.PAT}} | sudo docker login -u koteman123 --password-stdin
          sudo docker buildx create --use
          sudo docker buildx build --push --platform linux/arm64 -t ${{ steps.vars.outputs.img }} .
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: ./start_sanya.sh
      
    
        
